name: alochi_app
description: A'lochi — Gamified Education Platform
publish_to: none
version: 1.3.0+13

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dio: ^5.4.0
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.7
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  fl_chart: ^0.69.0
  confetti: ^0.7.0
  lottie: ^3.1.0
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  percent_indicator: ^4.2.3
  intl: ^0.20.2
  timeago: ^3.6.0
  equatable: ^2.0.5
  logger: ^2.0.2+1
  url_launcher: ^6.2.5
  flutter_secure_storage: ^10.0.0
  qr_flutter: ^4.1.0
  share_plus: ^10.0.0
  hive_flutter: ^1.1.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/branding/app-icon-1024.png"
  adaptive_icon_background: "#1F6F65"
  adaptive_icon_foreground: "assets/branding/app-icon-foreground.png"
  min_sdk_android: 24

flutter_native_splash:
  color: "#1F6F65"
  image: "assets/branding/splash-logo.png"
  android_12:
    color: "#1F6F65"
    image: "assets/branding/splash-logo.png"
  ios: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/branding/
